//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyResource.rc
//
#define MYERR_NOTEXTUREFILE             1
#define MYERR_NOMESHFILE                2
#define MYERR_CREATEVERTEXBUFFER        3
#define MYERR_CREATECUBEMAP             4
#define MYERR_CREATERENDERTOTEXTURE     5
#define MYERR_CREATEBUMPMAP             6
#define MYERR_CREATENORMALMAP           7
#define MYERR_CREATEVERTEXSHADER        8
#define MYERR_CREATEPIXELSHADER         9
#define MYERR_CREATEATTENUATIONMAP      10
#define MYERR_CREATEANISOTROPYMAP       11
#define MYERR_CREATEANISODIRMAP         12
#define MYERR_CREATESPECULARMAP         13
#define IDD_CHANGEMODEDLG               101
#define IDD_HELPDLG                     102
#define IDD_ABOUTDLG                    103
#define IDB_3DFX                        105
#define IDI_3DFX                        106
#define IDC_MODELIST                    1000
#define IDC_WINDOWMODE                  1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
