<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>shader</string>
	</array>
	<key>name</key>
	<string>Unity ShaderLab</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash.shaderlab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(Shader|Properties|Category|SubShader|Pass|Fog|LOD|Tags|Name|CGINCLUDE|CGPROGRAM|ENDCG|Fallback)\b</string>
			<key>name</key>
			<string>keyword.function.intrinsic.shaderlab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Render States</string>
			<key>match</key>
			<string>\b(Lighting|Cull|ZWrite|Blend|BlendOp|AlphaTest|Color|ColorMask|Offset|SeparateSpecular|ColorMaterial|SetTexture)((\s+(On|Off|Back|Front|Less|Greater|LEqual|GEqual|Equal|NotEqual|Always|One|Zero|SrcColor|SrcAlpha|DstColor|DstAlpha|OneMinusSrcColor|OneMinusSrcAlpha|OneMinusDstColor|OneMinusDstAlpha|Add|Sub|RevSub|Min|Max|LogicalClear|LogicalSet|LogicalCopy|LogicalCopyInverted|LogicalNoop|LogicalInvert|LogicalAnd|LogicalNand|LogicalOr|LogicalNor|LogicalXor|LogicalEquiv|LogicalAndReverse|LogicalAndInverted|LogicalOrReverse|LogicalOrInverted))+)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.shaderlab</string>
				</dict>
			</dict>
			<key>name</key>
			<string>keyword.function.intrinsic.shaderlab</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.shaderlab</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.shaderlab</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.shaderlab</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.cg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shaderlab</string>
	<key>uuid</key>
	<string>d0f40325-b2c2-4c34-9581-2a1ddb1fa8db</string>
</dict>
</plist>
